server:
  port: 80

---
#로컬
spring:
  config:
    activate:
      on-profile: "local"
  # DB Connection
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://52.78.247.211:3306/roggu?serverTimezone=Asia/Seoul&autoReconnect=true
      username: rogguh
      password: roggu123!@#
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging File Import
logging:
  config: classpath:log4j2.xml

---
#운영
spring:
  config:
    activate:
      on-profile: "real"